module.exports = {
  MAJOR_LEAGUE_ROLE_ID: "",
  MAJOR_LEAGUE_VOICE_CHANNEL_ID: "",
  MAJOR_LEAGUE_TEXT_CHANNEL_ID: "",
  ALTERNATIVE_LEAGUE_ROLE_ID: "",
  ALTERNATIVE_LEAGUE_TEXT_CHANNEL_ID: "",
  ALTERNATIVE_LEAGUE_VOICE_CHANNEL_ID: "",
  WELCOME_TEXT_CHANNEL_ID: "",
  SELECT_ROLE_CHANNEL_ID: "",
  BOT_ID: "",
  WAITING_LOBBY_VOICE_CHANNEL_ID: "",
  ADMIN_USER_ID: "",
  SERVER_ID: ""
}
